CREATE TABLE "RANKING" (
  "RANKING_ID" int PRIMARY KEY,
  "RANKING_DATE" date,
  "POSITION" int,
  "PLAYER_ID" int,
  "POINTS" int
);

CREATE TABLE "PLAYER" (
  "PLAYER_ID" int PRIMARY KEY,
  "NAME_FIRST" varchar(120),
  "NAME_LAST" varchar(120),
  "HAND" varchar(10),
  "BIRTH_DATE" date,
  "COUNTRY_CD" varchar(8),
  "HEIGHT" int,
  "WIKIDATA_ID" varchar(24)
);

CREATE TABLE "COUNTRY" (
  "COUNTRY_CD" varchar(8) PRIMARY KEY,
  "DESC" varchar(120)
);

CREATE TABLE "MATCH" (
  "MATCH_ID" int PRIMARY KEY,
  "TOURNEY_CD" varchar(24),
  "TOURNEY_DATE" date,
  "MATCH_NUM" int,
  "WINNER_ID" int,
  "WINNER_SEED" int,
  "WINNER_ENTRY_CD" varchar(4),
  "LOSER_ID" int,
  "LOSER_SEED" int,
  "LOSER_ENTRY_CD" varchar(4),
  "SCORE" varchar(60),
  "BEST_OF" int,
  "MATCH_ROUND_CD" varchar(8),
  "MINUTES" int,
  "W_ACE" int,
  "W_DF" int,
  "W_SV_PT" int,
  "W_1ST_LN" int,
  "W_1ST_WON" int,
  "W_2ST_WON" int,
  "W_SV_GMS" int,
  "W_BP_SAVED" int,
  "W_BP_FACED" int,
  "W_RANKING_ID" int,
  "L_ACE" int,
  "L_DF" int,
  "L_SV_PT" int,
  "L_1ST_LN" int,
  "L_1ST_WON" int,
  "L_2ST_WON" int,
  "L_SV_GMS" int,
  "L_BP_SAVED" int,
  "L_BP_FACED" int,
  "L_RANKING_ID" int
);

CREATE TABLE "TOURNEY" (
  "TOURNEY_CD" varchar(24) PRIMARY KEY,
  "TOURNEY_NAME" varchar(120),
  "SURFACE" varchar(30),
  "DRAW_SIZE" int,
  "LEVEL_CD" varchar(2)
);

CREATE TABLE "TOURNEY_LEVEL" (
  "LEVEL_CD" varchar(2) PRIMARY KEY,
  "DESC" varchar(120)
);

CREATE TABLE "ENTRY" (
  "ENTRY_CD" varchar(4) PRIMARY KEY,
  "ENTRY_DESC" varchar(120)
);

CREATE TABLE "MATCH_ROUND" (
  "MATCH_ROUND_CD" varchar(8) PRIMARY KEY,
  "DESC" varchar(120)
);

ALTER TABLE "RANKING" ADD FOREIGN KEY ("PLAYER_ID") REFERENCES "PLAYER" ("PLAYER_ID");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("WINNER_ID") REFERENCES "PLAYER" ("PLAYER_ID");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("LOSER_ID") REFERENCES "PLAYER" ("PLAYER_ID");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("W_RANKING_ID") REFERENCES "RANKING" ("RANKING_ID");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("L_RANKING_ID") REFERENCES "RANKING" ("RANKING_ID");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("TOURNEY_CD") REFERENCES "TOURNEY" ("TOURNEY_CD");

ALTER TABLE "TOURNEY" ADD FOREIGN KEY ("LEVEL_CD") REFERENCES "TOURNEY_LEVEL" ("LEVEL_CD");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("WINNER_ENTRY_CD") REFERENCES "ENTRY" ("ENTRY_CD");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("LOSER_ENTRY_CD") REFERENCES "ENTRY" ("ENTRY_CD");

ALTER TABLE "MATCH" ADD FOREIGN KEY ("MATCH_ROUND_CD") REFERENCES "MATCH_ROUND" ("MATCH_ROUND_CD");

ALTER TABLE "PLAYER" ADD FOREIGN KEY ("COUNTRY_CD") REFERENCES "COUNTRY" ("COUNTRY_CD");
